name: Build and Release Application

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Caching is not strictly necessary for this small project, but good practice
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # --- CHANGE: Specify the path to requirements.txt ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai_generated_code/requirements.txt  # Assuming it's in this subfolder
          pip install pyinstaller

      - name: Set up virtual display for macOS
        if: runner.os == 'macOS'
        run: |
          /usr/bin/sudo -v
          /usr/bin/sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.WindowServer.plist

      # --- CHANGE: Specify the path to the Python script ---
      - name: Build with PyInstaller
        # We also need to tell PyInstaller where to find the *other* .py file (fm_converter.py)
        # The --paths argument does this.
        run: pyinstaller --onefile --windowed --name "NHI-Converter-${{ matrix.os }}" --paths ai_generated_code ai_generated_code/NHI-GUI.py

      - name: Compress for macOS
        if: runner.os == 'macOS'
        run: zip -r NHI-Converter-macOS.zip dist/NHI-Converter-macOS.app
      
      - name: Compress for Windows
        if: runner.os == 'Windows'
        run: Compress-Archive -Path dist/NHI-Converter-Windows.exe -DestinationPath NHI-Converter-Windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NHI-Converter-${{ matrix.os }}
          path: NHI-Converter-*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          body_path: '' 
          files: artifacts/*/*.zip