name: Build and Release Application

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # --- THIS IS THE LINE TO CHANGE ---
      - name: Build with PyInstaller
        # Added --hidden-import=numpy to explicitly include it in the build.
        run: pyinstaller --onefile --windowed --name "NHI-Converter-${{ matrix.os }}" --hidden-import=numpy fm_converter_gui.py

      - name: Compress for macOS
        if: runner.os == 'macOS'
        run: zip -r NHI-Converter-macOS.zip dist/NHI-Converter-${{ matrix.os }}.app
      
      - name: Compress for Windows
        if: runner.os == 'Windows'
        run: Compress-Archive -Path dist/NHI-Converter-${{ matrix.os }}.exe -DestinationPath NHI-Converter-Windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NHI-Converter-${{ matrix.os }}
          path: NHI-Converter-*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          body_path: '' 
          files: artifacts/*/*.zip