name: Build and Release Application

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --onefile --windowed --name "NHI-Converter-${{ matrix.os }}" fm_converter_gui.py

      # --- CHANGES ARE IN THE NEXT TWO STEPS ---

      - name: Compress for macOS
        if: runner.os == 'macOS'
        # Corrected the path to match the PyInstaller output name
        run: zip -r NHI-Converter-macOS.zip dist/NHI-Converter-${{ matrix.os }}.app
      
      - name: Compress for Windows
        if: runner.os == 'Windows'
        # Corrected the path to match the PyInstaller output name
        run: Compress-Archive -Path dist/NHI-Converter-${{ matrix.os }}.exe -DestinationPath NHI-Converter-Windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NHI-Converter-${{ matrix.os }}
          # Corrected the file name to be more generic, will find either .zip file
          path: NHI-Converter-*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # This tells the release action to use the annotated tag message as the release notes.
          # You can create an annotated tag like: git tag -a v1.0.8 -m "This is a new release."
          body_path: '' 
          files: artifacts/*/*.zip